### ISSUE TITLE
Problems in app.py

### ISSUE THREAD

**Issue by cburke496** [wesny/CCVB#3]
When I tried running app.py it didn't work because there was a line that said 
"from py import Intagram"

I tried fixing the spelling but then it gave other errors, so I just commented the line out for now.

**Comment by cburke496** [comment]
Now I'm getting this error:

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from py import Instagram
  File "/home/students/2014/christopher.burke/CCVB/py/Instagram.py", line 1, in <module>
    import requests
ImportError: No module named requests
